pack-module with items relation commented
Markelfdez/Storio-Odoo pull request #4
Opened 2022-12-22 09:05 UTC by mlnnzr

2022-12-22 09:09 UTC, NicoRodBilbao requested changes
_packdata_ should be remove for now.

Do not comment the relations when merging onto the main branch.

2022-12-22 10:45 UTC, NicoRodBilbao approved these changes

2022-12-23 08:48 UTC, Markelfdez approved these changes
Looks good

2022-12-23 09:34 UTC, joana-renteria approved these changes
dale

2022-12-23 09:34 UTC, merged